
name: Deploy Bikeshare API

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.10"]

    steps:
      - uses: actions/checkout@v3

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v3
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies for the bikeshare model
        run: |
          python -m pip install --upgrade pip
          pip install -r bikeshare_project/requirements/test_requirements.txt

      - name: Train the bikeshare model and create the pkl file
        run: |
          python bikeshare_project/bikeshare_model/train_pipeline.py

      - name: Run pytest
        run: |
          pytest bikeshare_project/tests

      - name: Install the build package and run the build process on the bikeshare model to generate the wheel file
        run: |
          pip install --upgrade build
          python -m build bikeshare_project

    #   - name: Upload wheel file
    #     run: |
    #       ls -l bikeshare_project/dist
    #       cp bikeshare_project/dist/*.whl bikeshare_project/bike_sharing_api
    #       ls -l bikeshare_project/bike_sharing_api
      - name: Upload wheel file
        uses: actions/upload-artifact@v4
        with:
            name: bikeshare_model-0.0.1-py3-none-any.whl
            path: bikeshare_project/dist/*.whl

  docker:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Download wheel file
        uses: actions/download-artifact@v4
        with:
           name: bikeshare_model-0.0.1-py3-none-any.whl  
           path: bikeshare_project/bike_sharing_api

      - name: Build and push Docker image
        uses: docker/build-push-action@v6
        with:
          context: ./bikeshare_project/bike_sharing_api
          file: ./bikeshare_project/bike_sharing_api/Dockerfile
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/bikespare_api:latest



    

    
